import React from "react"
import {
  Activity,
  AlertOctagon,
  AlertTriangle,
  Archive,
  ArrowDownToLine,
  ArrowLeftRight,
  ArrowUpFromLine,
  BadgePercent,
  BarChart3,
  BellRing,
  Boxes,
  Building,
  CalendarArrowDown,
  CalendarArrowUp,
  CalendarCheck,
  Camera,
  CheckCircle2,
  CheckSquare,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cpu,
  ExternalLink,
  Factory,
  FileBadge,
  FileCheck2,
  FileSignature,
  FileSpreadsheet,
  FileText,
  FileUser,
  Flame,
  FolderCheck,
  HandCoins,
  History,
  Layers,
  ListOrdered,
  Lock,
  MapPin,
  MinusCircle,
  Network,
  Newspaper,
  PlusCircle,
  QrCode,
  Radio,
  ReceiptText,
  RefreshCcw,
  RotateCcw,
  SearchCheck,
  Send,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Store,
  TableProperties,
  Thermometer,
  UserCheck,
  UserPlus,
  Video,
  Warehouse,
  Workflow,
  Zap,
} from "lucide-react"

const ICON_MAP: Record<string, React.ComponentType<{ className?: string }>> = {
  Activity,
  AlertOctagon,
  AlertTriangle,
  Archive,
  ArrowDownToLine,
  ArrowLeftRight,
  ArrowUpFromLine,
  BadgePercent,
  BarChart3,
  BellRing,
  Boxes,
  Building,
  CalendarArrowDown,
  CalendarArrowUp,
  CalendarCheck,
  Camera,
  CheckCircle2,
  CheckSquare,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cpu,
  ExternalLink,
  Factory,
  FileBadge,
  FileCheck2,
  FileSignature,
  FileSpreadsheet,
  FileText,
  FileUser,
  Flame,
  FolderCheck,
  HandCoins,
  History,
  Layers,
  ListOrdered,
  Lock,
  MapPin,
  MinusCircle,
  Network,
  Newspaper,
  PlusCircle,
  QrCode,
  Radio,
  ReceiptText,
  RefreshCcw,
  RotateCcw,
  SearchCheck,
  Send,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Store,
  TableProperties,
  Thermometer,
  UserCheck,
  UserPlus,
  Video,
  Warehouse,
  Workflow,
  Zap,
}

export function IconRenderer({
  icon,
  className = "size-5",
}: {
  icon?: string
  className?: string
}) {
  if (!icon || !ICON_MAP[icon]) {
    return <Boxes className={className} />
  }
  const Component = ICON_MAP[icon]
  return <Component className={className} />
}
